[package]
name = "rust_server_sandbox"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.rocket]
version = "0.5.0-rc.3"
features = ["json"]

[dependencies]
wasm-logger = "0.2.0"
log = "0.4.6"